# 角色简体中文名字典(Dictionary)
characterSChineseDic = {
    'Reimu_Hakurei': '博丽灵梦',
    'Marisa_Kirisame': '雾雨魔理沙',
    # 'SinGyoku': '神玉',
    'Mima': '魅魔',
    # 'Kikuri': '菊理',
    'Konngara': '矜羯罗',
    # 'YuugenMagan': '幽幻魔眼',
    # 'Elis': '依莉斯',
    # 'Sariel': '萨丽爱尔',
    # 'Onmyou_gyoku': '阴阳玉',
    # 'Yamaaruki': '山步',
    'Genjii': '玄爷',
    'Rika': '里香',
    # 'Meira': '明罗',
    # 'Marisa': '魔梨沙',
    # 'Furawa_sensha': 'Flower～战车',
    # 'ibiruai_sigma': '邪眼西格玛',
    'Ellen': '爱莲',
    # 'Kotohime': '小兔姬',
    'Kana_Anaberal': '卡娜·安娜贝拉尔',
    # 'Asakura_Rikako': '朝仓理香子',
    'Chiyuri_Kitashirakawa': '北白河千百合',
    'Yumemi_Okazaki': '冈崎梦美',
    # 'Mimichan': '咪咪号',
    # 'Ru_koto': '留琴',
    # 'Ma_maru_chi': '玛玛露奇',
    # 'Sokuratesu': '苏格拉底',
    # 'Orange': '奥莲姬',
    'Kurumi': '胡桃',
    # 'Elliy': '艾丽',
    # 'Yuka': '幽香',
    # 'Mugetu': '梦月',
    # 'Gengetu': '幻月',
    'Sara': '萨拉',
    # 'Luize': '露易兹',
    # 'Alice': '爱丽丝',
    'Yuki': '雪',
    'Mai': '舞',
    'Yumeko': '梦子',
    'Shinki': '神绮',
    'Rumia': '露米娅',
    'Daiyousei': '大妖精',
    'Cirno': '琪露诺',
    'hong_meiling': '红美铃',
    'Koakuma': '小恶魔',
    'Patchouli_Knowledge': '帕秋莉·诺蕾姬',
    'Sakuya_Izayoi': '十六夜咲夜',
    'Remilia_Scarlet': '蕾米莉亚·斯卡蕾特',
    'Flandre_Scarlet': '芙兰朵露·斯卡蕾特',
    'Rin_Satsuki': '冴月麟',
    # 'Kedama': '毛玉',
    'Letty_Whiterock': '蕾蒂·霍瓦特洛克',
    'Chen': '橙',
    'Alice_Margatroid': '爱丽丝·玛格特洛依德',
    'Lily_White': '莉莉霍瓦特',
    'Lunasa_Prismriver': '露娜萨·普莉兹姆利巴',
    'Merlin_Prismriver': '梅露兰·普莉兹姆利巴',
    'Lyrica_Prismriver': '莉莉卡·普莉兹姆利巴',
    'Youmu_Konpaku': '魂魄妖梦',
    'Yuyuko_Saigyouji': '西行寺幽幽子',
    'Ran_Yakumo': '八云蓝',
    'Yukari_Yakumo': '八云紫',
    'Youki_Konpaku': '魂魄妖忌',
    # 'Leira_Prismriver': '蕾拉·普莉兹姆利巴',
    'Suika_Ibuki': '伊吹萃香',
    'Wriggle_Nightbug': '莉格露·奈特巴格',
    'Mystia_Lorelei': '米斯蒂娅·萝蕾拉',
    'Keine_Kamishirasawa': '上白泽慧音',
    'Tewi_Inaba': '因幡天为（因幡帝）',
    'Reisen_Udongein_Inaba': '铃仙·优昙华院·因幡',
    'Eirin_Yagokoro': '八意永琳',
    'Kaguya_Houraisan': '蓬莱山辉夜',
    'fujiwara_no_mokou': '藤原妹红',
    'Aya_Shameimaru': '射命丸文',
    'Medicine_Melancholy': '梅蒂欣·梅兰可莉',
    'Yuuka_Kazami': '风见幽香',
    'Komachi_Onozuka': '小野塚小町',
    'Shikieiki_Yamaxanadu': '四季映姬·亚玛撒那度',
    'Shizuha_Aki': '秋静叶',
    'Minoriko_Aki': '秋穰子',
    'Hina_Kagiyama': '键山雏',
    'nitori_kawashiro': '河城荷取',
    'momiji_inubashiri': '犬走椛',
    'Kochiya_Sanae': '东风谷早苗',
    'Kanako_Yasaka': '八坂神奈子',
    'Suwako_Moriya': '洩矢诹访子',
    'Iku_Nagae': '永江衣玖',
    'tenshi_hinanai': '比那名居天子',
    'Kisume': '琪斯美',
    'Yamame_Kurodani': '黑谷山女',
    'Parsee_Mizuhashi': '水桥帕露西',
    'yuugi_hoshiguma': '星熊勇仪',
    'Satori_Komeiji': '古明地觉',
    'Rin_Kaenbyou': '火焰猫燐',
    'utsuho_reiuji': '灵乌路空',
    'Koishi_Komeiji': '古明地恋',
    'Nazrin': '娜兹玲',
    'Kogasa_Tatara': '多多良小伞',
    'ichirin_kumoi': '云居一轮',
    'Unzan': '云山',
    'minamitsu_murasa': '村纱水蜜',
    'shou_toramaru': '寅丸星',
    'byakuren_hijiri': '圣白莲',
    'Nue_Houjuu': '封兽鵺',
    # 'Myouren': '命莲',
    # 'Oo-Namazu': '大鲶鱼',
    # 'Taisai Sei-kun': '太岁星君',
    # 'Daidarabotchi': '大太法师',
    # 'Hisoutensoku': '非想天则',
    # 'Titania': '提泰妮娅',
    # 'Goliath_Doll': '歌利亚人偶',
    'Hatate_Himekaidou': '姬海棠果',
    'Kyouko_Kasodani': '幽谷响子',
    'Yoshika_Miyako': '宫古芳香',
    'seiga_kaku': '霍青娥',
    'soga_no_tojiko': '苏我屠自古',
    'Mononobe_no_Futo': '物部布都',
    'Toyosatomimi_no_Miko': '丰聪耳神子',
    'mamizou_futatsuiwa': '二岩猯藏',
    'Hata_no_Kokoro': '秦心',
    # 'Hata_no_Kawakatsu': '秦河胜',
    'Wakasagihime': '若鹭姬',
    'Sekibanki': '赤蛮奇',
    'kagerou_imaizumi': '今泉影狼',
    'Benben_Tsukumo': '九十九弁弁',
    'Yatsuhashi_Tsukumo': '九十九八桥',
    'Seija_Kijin': '鬼人正邪',
    'Shinmyoumaru_Sukuna': '少名针妙丸',
    'Raiko_Horikawa': '堀川雷鼓',
    'Sumireko_Usami': '宇佐见堇子',
    'Seiran': '清兰',
    'Ringo': '铃瑚',
    'Doremy_Sweet': '哆来咪·苏伊特',
    'sagume_kishin': '稀神探女',
    'Clownpiece': '克劳恩皮丝',
    'Junko': '纯狐',
    'Hecatia_Lapislazuli': '赫卡提亚·拉碧斯拉祖利',
    'joon_yorigami': '依神女苑',
    'shion_yorigami': '依神紫苑',
    'Eternity_Larva': '爱塔妮缇拉尔瓦',
    'Nemuno_Sakata': '坂田合欢',
    'Aunn_Komano': '高丽野阿吽',
    'Narumi_Yatadera': '矢田寺成美',
    'Satono_Nishida': '尔子田里乃',
    'Mai_Teireida': '丁礼田舞',
    'Okina_Matara': '摩多罗隐岐奈',
    # 'Ebisu_Eika': '戎璎花',
    'Urumi_Ushizaki': '牛崎润美',
    'Kutaka_Niwatari': '庭渡久侘歌',
    # 'Yachie_Kitcho': '吉吊八千慧',
    'Mayumi_Joutougu': '杖刀偶磨弓',
    'Keiki_Haniyasushin': '埴安神袿姬',
    # 'Saki_Kurokoma': '骊驹早鬼',
    'Rinnosuke_Morichika': '森近霖之助',
    'Tokiko': '朱鹭子',
    # 'Kawauso_no_Shoujyo': '水獭少女',
    'Sunny_Milk': '桑尼米尔克',
    'Luna_Child': '露娜切露德',
    'Star_Sapphire': '斯塔萨菲雅',
    'Watatsuki_no_Toyohime': '绵月丰姬',
    'Watatsuki_no_Yorihime': '绵月依姬',
    # 'Reisen': '铃仙二号',
    'Hieda_no_Akyuu': '稗田阿求',
    'kasen_ibara': '茨木华扇',
    # 'Ibaraki_Douji_no_Ude': '茨木童子之臂',
    # 'Koutei': '黄帝',
    # 'Kume': '久米',
    # 'Mukou': '务光',
    # 'Sendai_Shirou': '仙台四郎',
    # 'Kanda': '竿打',
    # 'Houso': '彭祖',
    # 'Zashiki_warashi': '座敷童子',
    # 'Hobgoblin': '地精',
    # 'Manzairaku': '万岁乐',
    'Kosuzu_Motoori': '本居小铃',
    # 'Enenra': '烟烟罗',
    # 'Chupacabra': '卓柏卡布拉',
    # 'JyaRyu': '邪龙',
    # 'Kutsutsura': '沓颊',
    # 'Shoujo_no_Onryou': '怨灵少女',
    # 'Yuuten_Shyounin': '祐天上人',
    # 'The Fortune-teller': '易者',
    # 'Anxious Moustached Villager': '长相酷似周杰伦的村民',
    # 'Salt Merchant': '盐家老板',
    # 'Unnamed Umatsuki': '马凭',
    # 'Kanami': '观阿弥',
    # 'Zeami': '世阿弥',
    # 'Okunoda_Miyoi': '奥野田美宵',
}
