# 角色罗马音列表(List)
characterRomanizationList = [
    'Reimu_Hakurei',
    'Marisa_Kirisame',
    # 'SinGyoku',
    'Mima',
    # 'Kikuri',
    'Konngara',
    # 'YuugenMagan',
    # 'Elis',
    # 'Sariel',
    # 'Onmyou_gyoku',
    # 'Yamaaruki',
    'Genjii',
    'Rika',
    # 'Meira',
    # 'Marisa',
    # 'Furawa_sensha',
    # 'ibiruai_sigma',
    'Ellen',
    # 'Kotohime',
    'Kana_Anaberal',
    # 'Asakura_Rikako',
    'Chiyuri_Kitashirakawa',
    'Yumemi_Okazaki',
    # 'Mimichan',
    'Ru_koto',
    # 'Ma_maru_chi',
    # 'Sokuratesu',
    # 'Orange',
    'Kurumi',
    # 'Elliy',
    # 'Yuka',
    # 'Mugetu',
    # 'Gengetu',
    'Sara',
    # 'Luize',
    # 'Alice',
    'Yuki',
    'Mai',
    'Yumeko',
    'Shinki',
    'Rumia',
    'Daiyousei',
    'Cirno',
    'hong_meiling',
    'Koakuma',
    'Patchouli_Knowledge',
    'Sakuya_Izayoi',
    'Remilia_Scarlet',
    'Flandre_Scarlet',
    'Rin_Satsuki',
    # 'Kedama',
    'Letty_Whiterock',
    'Chen',
    'Alice_Margatroid',
    'Lily_White',
    'Lunasa_Prismriver',
    'Merlin_Prismriver',
    'Lyrica_Prismriver',
    'Youmu_Konpaku',
    'Yuyuko_Saigyouji',
    'Ran_Yakumo',
    'Yukari_Yakumo',
    'Youki_Konpaku',
    'Leira_Prismriver',
    'Suika_Ibuki',
    'Wriggle_Nightbug',
    'Mystia_Lorelei',
    'Keine_Kamishirasawa',
    'Tewi_Inaba',
    'Reisen_Udongein_Inaba',
    'Eirin_Yagokoro',
    'Kaguya_Houraisan',
    'fujiwara_no_mokou',
    'Aya_Shameimaru',
    'Medicine_Melancholy',
    'Yuuka_Kazami',
    'Komachi_Onozuka',
    'Shikieiki_Yamaxanadu',
    'Shizuha_Aki',
    'Minoriko_Aki',
    'Hina_Kagiyama',
    'nitori_kawashiro',
    'momiji_inubashiri',
    'Kochiya_Sanae',
    'Kanako_Yasaka',
    'Suwako_Moriya',
    'Iku_Nagae',
    'tenshi_hinanai',
    'Kisume',
    'Yamame_Kurodani',
    'Parsee_Mizuhashi',
    'yuugi_hoshiguma',
    'Satori_Komeiji',
    'Rin_Kaenbyou',
    'utsuho_reiuji',
    'Koishi_Komeiji',
    'Nazrin',
    'Kogasa_Tatara',
    'ichirin_kumoi',
    'Unzan',
    'minamitsu_murasa',
    'shou_toramaru',
    'byakuren_hijiri',
    'Nue_Houjuu',
    # 'Myouren',
    # 'Oo-Namazu',
    # 'Taisai Sei-kun',
    # 'Daidarabotchi',
    # 'Hisoutensoku',
    # 'Titania',
    # 'Goliath_Doll',
    'Hatate_Himekaidou',
    'Kyouko_Kasodani',
    'Yoshika_Miyako',
    'seiga_kaku',
    'soga_no_tojiko',
    'Mononobe_no_Futo',
    'Toyosatomimi_no_Miko',
    'mamizou_futatsuiwa',
    'Hata_no_Kokoro',
    # 'Hata_no_Kawakatsu',
    'Wakasagihime',
    'Sekibanki',
    'kagerou_imaizumi',
    'Benben_Tsukumo',
    'Yatsuhashi_Tsukumo',
    'Seija_Kijin',
    'Shinmyoumaru_Sukuna',
    'Raiko_Horikawa',
    'Sumireko_Usami',
    'Seiran',
    'Ringo',
    'Doremy_Sweet',
    'sagume_kishin',
    'Clownpiece',
    'Junko',
    'Hecatia_Lapislazuli',
    'joon_yorigami',
    'shion_yorigami',
    'Eternity_Larva',
    'Nemuno_Sakata',
    'Aunn_Komano',
    'Narumi_Yatadera',
    'Satono_Nishida',
    'Mai_Teireida',
    'Okina_Matara',
    # 'Ebisu_Eika',
    'Urumi_Ushizaki',
    'Kutaka_Niwatari',
    # 'Yachie_Kitcho',
    'Mayumi_Joutougu',
    'Keiki_Haniyasushin',
    # 'Saki_Kurokoma',
    'Rinnosuke_Morichika',
    'Tokiko',
    # 'Kawauso_no_Shoujyo',
    'Sunny_Milk',
    'Luna_Child',
    'Star_Sapphire',
    'Watatsuki_no_Toyohime',
    'Watatsuki_no_Yorihime',
    # 'Reisen',
    'Hieda_no_Akyuu',
    'kasen_ibara',
    # 'Ibaraki_Douji_no_Ude',
    # 'Koutei',
    # 'Kume',
    # 'Mukou',
    # 'Sendai_Shirou',
    # 'Kanda',
    # 'Houso',
    # 'Zashiki_warashi',
    # 'Hobgoblin',
    # 'Manzairaku',
    'Kosuzu_Motoori',
    # 'Enenra',
    # 'Chupacabra',
    # 'JyaRyu',
    # 'Kutsutsura',
    # 'Shoujo_no_Onryou',
    # 'Yuuten_Shyounin',
    # 'The Fortune-teller',
    # 'Anxious Moustached Villager',
    # 'Salt Merchant',
    # 'Unnamed Umatsuki',
    # 'Kanami',
    # 'Zeami',
    # 'Okunoda_Miyoi',
]
